import os

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))

# LLM Settings
LLM_NAME="LLM_NAME"
ENABLE_HISTROY="ENABLE_HISTROY"

# Customize LLM Settings
## OpenAI
OPENAI_API_BASE = "OPENAI_API_BASE"
OPENAI_API_KEY = "OPENAI_API_KEY"
OPENAI_MODEL_NAME = "OPENAI_MODEL_NAME"

## Ollama
OLLAMA_MODEL_NAME = "OLLAMA_MODEL_NAME"

# Embedding Settings
EMBEDDING_MODEL_NAME="EMBEDDING_MODEL_NAME"
EMBEDDING_FILE_PATH="EMBEDDING_FILE_PATH"
REFRESH_VECTORDB="REFRESH_VECTORDB"
DEVICE="DEVICE"
CHUNK_SIZE="CHUNK_SIZE"
CHUNK_OVERLAP="CHUNK_OVERLAP"

# Reranker Settings
RERANK_MODEL_NAME="RERANK_MODEL_NAME"
SIMILARITY_TOP_K="SIMILARITY_TOP_K"
RERANK_TOP_K="RERANK_TOP_K"

# History Memory Settings
LATEST_HISTORY_NUMS = "LATEST_HISTORY_NUMS"
MEMORY_CONNECTION_STRING = "MEMORY_CONNECTION_STRING"
MEMORY_DATABASE_NAME = "MEMORY_DATABASE_NAME"
MEMORY_COLLECTION_NAME = "MEMORY_COLLECTION_NAME"
SESSION_ID = "SESSION_ID"
MONGO_USERNAME = "MONGO_USERNAME"
MONGO_PASSWORD = "MONGO_PASSWORD"
MONGO_CLUSTER = "MONGO_CLUSTER"
MEMORY_WINDOW_SIZE = "MEMORY_WINDOW_SIZE"
MONGO_DATABASE = "MONGO_DATABASE"
MONGO_COLLECTION = "MONGO_COLLECTION"
MONGO_CONNECTION_STRING = "MONGO_CONNECTION_STRING"

# Other Settings
AI_PREFIX = "AI_PREFIX"
HUMAN_PREFIX = "HUMAN_PREFIX"
MEMORY_KEY = "MEMORY_KEY"